### ISSUE TITLE
Syntax Error!

### ISSUE THREAD

**Issue by micael333** [theDreamer911/brute-force-instagram#11]
Traceback (most recent call last):
  File "C:\Users\micae\PycharmProjects\abc123\instagram-brute-force.py", line 14, in <module>
    web = Browser()
  File "C:\Users\micae\PycharmProjects\abc123\venv\lib\site-packages\webbot\webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
  File "C:\Users\micae\PycharmProjects\abc123\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\micae\PycharmProjects\abc123\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\micae\PycharmProjects\abc123\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\micae\PycharmProjects\abc123\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\micae\PycharmProjects\abc123\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 10.0.19042 x86_64)

**Comment by theDreamer911** [comment]
You should download chrome binary first. Actually I forgot about it in the article, well, just find the way to install chrome binary, hope this advice works
