### ISSUE TITLE
init() error

### ISSUE THREAD

**Issue by t2ncay** [theDreamer911/brute-force-instagram#15]
Traceback (most recent call last):
  File "instagram-brute-force.py", line 14, in <module>
    web = Browser()
  File "C:\Users\Samsung-2010\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webbot\webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
TypeError: __init__() got an unexpected keyword argument 'options'

how can I fix it?

**Comment by theDreamer911** [comment]
you can try search webdriver manually. It will make webbot displaying browser
