### ISSUE TITLE
webbot not being recognized when opening browser(OS linux mint 20.x)

### ISSUE THREAD

**Issue by santossousa** [theDreamer911/brute-force-instagram#17]
Traceback (most recent call last):
  File "instagram-brute-force.py", line 14, in <module>
    web = Browser()
  File "/home/fabio/.local/lib/python3.8/site-packages/webbot/webbot.py", line 72, in __init__
    [setattr(self, function, getattr(self.driver, function)) for function in
  File "/home/fabio/.local/lib/python3.8/site-packages/webbot/webbot.py", line 72, in <listcomp>
    [setattr(self, function, getattr(self.driver, function)) for function in
AttributeError: 'WebDriver' object has no attribute 'switch_to_alert

**Comment by theDreamer911** [comment]
Actually, I have never tested it in a Linux environment, but I think you still can install it, by finding how to use webbot in Linux mint
