### ISSUE TITLE
it is showing this type of errors what to do can anyone help

### ISSUE THREAD

**Issue by androiddevelope** [theDreamer911/brute-force-instagram#19]
Traceback (most recent call last):
  File "C:\Users\ABHIRAM\PycharmProjects\bruteforce\main.py", line 14, in <module>
    web=Browser()
  File "C:\Users\ABHIRAM\PycharmProjects\bruteforce\venv\lib\site-packages\webbot\webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
  File "C:\Users\ABHIRAM\PycharmProjects\bruteforce\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\ABHIRAM\PycharmProjects\bruteforce\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\ABHIRAM\PycharmProjects\bruteforce\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\ABHIRAM\PycharmProjects\bruteforce\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\ABHIRAM\PycharmProjects\bruteforce\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ABHIRAM\PycharmProjects\bruteforce\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 10.0.19043 x86_64)

**Comment by theDreamer911** [comment]
Your error is in here

`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary`

Just find the way to download and use Chrome binary and it will be worked

**Comment by theDreamer911** [comment]
The error is the same as previous issues [#7 ](https://github.com/theDreamer911/brute-force-instagram/issues/7)
