### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ripe02** [theDreamer911/brute-force-instagram#21]
Traceback (most recent call last):
  File "/home/kali/brute-force-instagram/instagram-brute-force.py", line 14, in <module>
    web = Browser()
  File "/home/kali/.local/lib/python3.9/site-packages/webbot/webbot.py", line 68, in __init__
    self.driver = webdriver.Chrome(executable_path=driverpath, options=options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 5.14.0-kali4-amd64 x86_64)

**Comment by theDreamer911** [comment]
The error is the same as previous issues [#7 ](https://github.com/theDreamer911/brute-force-instagram/issues/7)
