### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jigsaw678** [theDreamer911/brute-force-instagram#6]
```
Choose Dictionary: dictionary
Traceback (most recent call last):
  File "/home/odin/brute-force-instagram/instagram-brute-force.py", line 14, in <module>
    web = Browser()
  File "/home/odin/.local/lib/python3.9/site-packages/webbot/webbot.py", line 72, in __init__
    [setattr(self, function, getattr(self.driver, function)) for function in
  File "/home/odin/.local/lib/python3.9/site-packages/webbot/webbot.py", line 72, in <listcomp>
    [setattr(self, function, getattr(self.driver, function)) for function in
AttributeError: 'WebDriver' object has no attribute 'switch_to_alert'
```

**Comment by theDreamer911** [comment]
Did you install webbot correctly?
